name: teleop_test
channels:
  - pytorch
  - speleo3
  - robostack
  - robostack-experimental
  - conda-forge
  - defaults
dependencies:
  - fastdtw
  - aesara
  - deepdiff
  - pygraphviz
  - arviz
  - assimp
  - autograd
  - beautifulsoup4
  - binutils
  - bullet
  - catkin_pkg
  - catkin_tools
  - cffi=1.14.2
  - cmake
  - cudatoolkit
  - curl
  - cython
  - eigen
  - fcl
  - future
  - gcc
  - gdown
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter
  - leap-motion-python
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pip
  - pymc3
  - pyqt
  - python=3.8.12
  - pyyaml
  - qpsolvers
  - qt
  - roboticstoolbox-python
  - ros-galactic-desktop
  - rosdep
  - rosdistro
  - rospkg
  - rtb-data
  - scikit-learn
  - scipy
  - seaborn
  - sip
  - spatialgeometry
  - spatialmath-python
  - swift-sim
  - swig
  - sympy
  - torchaudio
  - torchvision
  - yaml
  - freeglut
  - ros-galactic-panda-moveit-config
  - ros-galactic-control-msgs
  - pip:
    - machinevision-toolbox-python==0.5.5
    - opencv-python==4.5.5.62
    - autograd
    - transformations
