name: teleopenv
channels:
- conda-forge
- robostack-staging
dependencies:
- python=3.11 # Make sure the correct Leap Python version is installed (https://github.com/petrvancjr/LeapAPI)
- numpy
- pymc
- fastdtw
- scikit-learn
- seaborn
- ros-humble-desktop
- ros-humble-rosbridge-server
- spatialmath-python
- compilers # ROS2 utils
- cmake
- pkg-config
- make
- colcon-common-extensions
- rosdep
- pip:
  - transformations==2021.6.6