name: teleopenv2
channels:
  - conda-forge
  - speleo3
  - robostack
  - robostack-experimental
  - defaults
dependencies:
  - fastdtw
  - deepdiff
  - pygraphviz
  - arviz
  - assimp
  - autograd
  - beautifulsoup4
  - binutils
  - bullet
  - cmake
  - curl
  - cython
  - eigen
  - fcl
  - future
  - gcc
  - gdown
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pip
  - pymc3
  - pyqt
  - python=3.9
  - pyyaml
  - qpsolvers
  - qt
  - roboticstoolbox-python
  - rtb-data
  - scikit-learn
  - scipy
  - seaborn
  - sip
  - spatialgeometry
  - spatialmath-python
  - swift-sim
  - swig
  - sympy
  - yaml
  - freeglut
  - rosdep
  - rosdistro
  - rospkg
  - ros-galactic-desktop
  - ros-galactic-moveit-resources-panda-moveit-config
  - ros-galactic-control-msgs
  - ros-galactic-moveit-msgs
  - pip:
    - cffi==1.14.2
    - machinevision-toolbox-python==0.5.5
    #- opencv-python==4.5.5.62
    - autograd
    - transformations
