name: teleop_test
channels:
  - pytorch
  - speleo3
  - robostack
  - robostack-experimental
  - conda-forge
  - defaults
dependencies:
  - fastdtw
  - aesara
  - deepdiff
  - pygraphviz
  - arviz
  - assimp
  - autograd
  - beautifulsoup4
  - binutils
  - bullet
  - catkin_pkg
  - catkin_tools
  - cffi=1.14.2
  - cmake
  - cudatoolkit
  - curl
  - cython
  - eigen
  - fcl
  - future
  - gcc
  - gdown
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter
  - leap-motion-python
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pip
  - pymc3
  - pyqt
  - python=3.8.12
  - pyyaml
  - qpsolvers
  - qt
  - roboticstoolbox-python
  - ros-noetic-py-trees
  - ros-noetic-py-trees-msgs
  - ros-noetic-py-trees-ros
  - ros-distro-mutex
  - ros-noetic-actionlib
  - ros-noetic-actionlib-msgs
  - ros-noetic-actionlib-tutorials
  - ros-noetic-angles
  - ros-noetic-bond
  - ros-noetic-bond-core
  - ros-noetic-bondcpp
  - ros-noetic-bondpy
  - ros-noetic-catkin
  - ros-noetic-class-loader
  - ros-noetic-cmake-modules
  - ros-noetic-common-msgs
  - ros-noetic-common-tutorials
  - ros-noetic-control-msgs
  - ros-noetic-cpp-common
  - ros-noetic-cv-bridge
  - ros-noetic-desktop
  - ros-noetic-diagnostic-aggregator
  - ros-noetic-diagnostic-analysis
  - ros-noetic-diagnostic-common-diagnostics
  - ros-noetic-diagnostic-msgs=1.13.1
  - ros-noetic-diagnostic-updater=1.10.3
  - ros-noetic-diagnostics
  - ros-noetic-dynamic-reconfigure
  - ros-noetic-eigen-conversions
  - ros-noetic-eigen-stl-containers
  - ros-noetic-executive-smach
  - ros-noetic-filters
  - ros-noetic-gencpp
  - ros-noetic-geneus
  - ros-noetic-genlisp
  - ros-noetic-genmsg
  - ros-noetic-gennodejs
  - ros-noetic-genpy
  - ros-noetic-geometric-shapes
  - ros-noetic-geometry
  - ros-noetic-geometry-msgs
  - ros-noetic-geometry-tutorials
  - ros-noetic-gl-dependency
  - ros-noetic-graph-msgs
  - ros-noetic-image-transport
  - ros-noetic-interactive-marker-tutorials
  - ros-noetic-interactive-markers
  - ros-noetic-joint-state-publisher
  - ros-noetic-joint-state-publisher-gui
  - ros-noetic-kdl-conversions
  - ros-noetic-kdl-parser
  - ros-noetic-laser-geometry
  - ros-noetic-librviz-tutorial
  - ros-noetic-map-msgs
  - ros-noetic-media-export
  - ros-noetic-message-filters
  - ros-noetic-message-generation
  - ros-noetic-message-runtime=
  - ros-noetic-mk
  - ros-noetic-moveit-core
  - ros-noetic-moveit-msgs
  - ros-noetic-moveit-ros-occupancy-map-monitor
  - ros-noetic-moveit-ros-planning
  - ros-noetic-moveit-visual-tools
  - ros-noetic-nav-msgs
  - ros-noetic-nodelet
  - ros-noetic-nodelet-core
  - ros-noetic-nodelet-topic-tools
  - ros-noetic-nodelet-tutorial-math
  - ros-noetic-object-recognition-msgs
  - ros-noetic-octomap
  - ros-noetic-octomap-msgs
  - ros-noetic-pluginlib
  - ros-noetic-pluginlib-tutorials
  - ros-noetic-python-qt-binding
  - ros-noetic-qt-dotgraph
  - ros-noetic-qt-gui
  - ros-noetic-qt-gui-cpp
  - ros-noetic-qt-gui-py-common
  - ros-noetic-qwt-dependency
  - ros-noetic-random-numbers
  - ros-noetic-resource-retriever
  - ros-noetic-robot
  - ros-noetic-robot-state-publisher
  - ros-noetic-ros
  - ros-noetic-ros-base
  - ros-noetic-ros-comm
  - ros-noetic-ros-core
  - ros-noetic-ros-environment
  - ros-noetic-ros-tutorials
  - ros-noetic-rosbag
  - ros-noetic-rosbag-migration-rule
  - ros-noetic-rosbag-storage
  - ros-noetic-rosbash
  - ros-noetic-rosboost-cfg
  - ros-noetic-rosbuild
  - ros-noetic-rosclean
  - ros-noetic-rosconsole
  - ros-noetic-rosconsole-bridge
  - ros-noetic-roscpp
  - ros-noetic-roscpp-core
  - ros-noetic-roscpp-serialization
  - ros-noetic-roscpp-traits
  - ros-noetic-roscpp-tutorials
  - ros-noetic-roscreate
  - ros-noetic-rosgraph
  - ros-noetic-rosgraph-msgs
  - ros-noetic-roslang
  - ros-noetic-roslaunch
  - ros-noetic-roslib
  - ros-noetic-roslint
  - ros-noetic-roslisp
  - ros-noetic-roslz4
  - ros-noetic-rosmake
  - ros-noetic-rosmaster
  - ros-noetic-rosmsg
  - ros-noetic-rosnode
  - ros-noetic-rosout
  - ros-noetic-rospack
  - ros-noetic-rosparam
  - ros-noetic-rospy
  - ros-noetic-rospy-tutorials
  - ros-noetic-rosservice
  - ros-noetic-rostest
  - ros-noetic-rostime
  - ros-noetic-rostopic
  - ros-noetic-rosunit
  - ros-noetic-roswtf
  - ros-noetic-rqt-action
  - ros-noetic-rqt-bag
  - ros-noetic-rqt-bag-plugins
  - ros-noetic-rqt-common-plugins
  - ros-noetic-rqt-console
  - ros-noetic-rqt-dep
  - ros-noetic-rqt-graph
  - ros-noetic-rqt-gui
  - ros-noetic-rqt-gui-cpp
  - ros-noetic-rqt-gui-py
  - ros-noetic-rqt-image-view
  - ros-noetic-rqt-launch
  - ros-noetic-rqt-logger-level
  - ros-noetic-rqt-moveit
  - ros-noetic-rqt-msg
  - ros-noetic-rqt-nav-view
  - ros-noetic-rqt-plot
  - ros-noetic-rqt-pose-view
  - ros-noetic-rqt-publisher
  - ros-noetic-rqt-py-common
  - ros-noetic-rqt-py-console
  - ros-noetic-rqt-reconfigure
  - ros-noetic-rqt-robot-dashboard
  - ros-noetic-rqt-robot-monitor
  - ros-noetic-rqt-robot-plugins
  - ros-noetic-rqt-robot-steering
  - ros-noetic-rqt-runtime-monitor
  - ros-noetic-rqt-rviz
  - ros-noetic-rqt-service-caller
  - ros-noetic-rqt-shell
  - ros-noetic-rqt-srv
  - ros-noetic-rqt-tf-tree
  - ros-noetic-rqt-top
  - ros-noetic-rqt-topic
  - ros-noetic-rqt-web
  - ros-noetic-rviz
  - ros-noetic-rviz-plugin-tutorials
  - ros-noetic-rviz-python-tutorial
  - ros-noetic-rviz-visual-tools
  - ros-noetic-self-test
  - ros-noetic-sensor-msgs
  - ros-noetic-shape-msgs
  - ros-noetic-smach
  - ros-noetic-smach-msgs
  - ros-noetic-smach-ros
  - ros-noetic-smclib
  - ros-noetic-srdfdom
  - ros-noetic-std-msgs
  - ros-noetic-std-srvs
  - ros-noetic-stereo-msgs
  - ros-noetic-tf
  - ros-noetic-tf-conversions
  - ros-noetic-tf2
  - ros-noetic-tf2-eigen
  - ros-noetic-tf2-geometry-msgs
  - ros-noetic-tf2-kdl
  - ros-noetic-tf2-msgs
  - ros-noetic-tf2-py
  - ros-noetic-tf2-ros
  - ros-noetic-topic-tools
  - ros-noetic-trajectory-msgs
  - ros-noetic-turtle-actionlib
  - ros-noetic-turtle-tf
  - ros-noetic-turtle-tf2
  - ros-noetic-turtlesim
  - ros-noetic-urdf
  - ros-noetic-urdf-parser-plugin
  - ros-noetic-urdf-tutorial
  - ros-noetic-urdfdom-py
  - ros-noetic-visualization-marker-tutorials
  - ros-noetic-visualization-msgs
  - ros-noetic-visualization-tutorials
  - ros-noetic-viz
  - ros-noetic-webkit-dependency
  - ros-noetic-xacro
  - ros-noetic-xmlrpcpp
  - rosdep
  - rosdistro
  - rospkg
  - rtb-data
  - scikit-learn
  - scipy
  - seaborn
  - sip
  - spatialgeometry
  - spatialmath-python
  - swift-sim
  - swig
  - sympy
  - torchaudio
  - torchvision
  - yaml
  - freeglut
  - ros-noetic-panda-moveit-config
  - pip:
    - machinevision-toolbox-python==0.5.5
    - opencv-python==4.5.5.62
    - autograd
