
bool circle_present
int64 circle_id
bool circle_in_progress
bool circle_clockwise
float64 circle_progress
float64 circle_angle
float64 circle_radius
int32 circle_state

bool swipe_present
int64 swipe_id
bool swipe_in_progress
float64[3] swipe_direction
float64 swipe_speed
int32 swipe_state

bool keytap_present
int64 keytap_id
bool keytap_in_progress
float64[3] keytap_direction
float64[3] keytap_position
int32 keytap_state

bool screentap_present
int64 screentap_id
bool screentap_in_progress
float64[3] screentap_direction
float64[3] screentap_position
int32 screentap_state
