# Picks set from configurations:
# Each set chooses the suitable gestures, mappings, etc..
using_config: main_set

available_configurations:
  main_set:
    gestures: main_set
    mapping: main_map

    static_detection_approach: PyMC3
    dynamic_detection_approach: DTW
    static_network_file: PyMC3-main-set-3.pkl
    dynamic_network_file: promp
    hand_mode_l: static
    hand_mode_r: dynamic
  set_1_static:
    gestures: set_1_static
    mapping: set_1_static

    static_detection_approach: PyMC3
    dynamic_detection_approach: PyTorch
    static_network_file: network0.pkl
    dynamic_network_file:
    hand_mode_l: static
    hand_mode_r: dynamic
  main_set_static:
    gestures: main_set_static
    mapping: main_set_static

    static_detection_approach: PyMC3
    dynamic_detection_approach: DTW
    static_network_file: PyMC3-main-set-3.pkl
    dynamic_network_file: promp
    hand_mode_l: static
    hand_mode_r: none
  new_gesture_set:
    gestures: new_gesture_set

    static_detection_approach: PyMC3
    dynamic_detection_approach: DTW
    static_network_file: new_network.pkl #
    dynamic_network_file: promp
    hand_mode_l: static
    hand_mode_r: dynamic

min_confidence: 0.3
since_frame_time: 0.5
touch_turn_on_dist: [0.9, 0.9, 0.9, 0.9,  0.9, 0.9, 0.9]
touch_turn_off_dist: [0.5, 0.5, 0.5, 0.5,  0.5, 0.5, 0.5]
oc_turn_on_thre: [0.94, 0.8, 0.8, 0.8, 0.8]
oc_turn_off_thre: [0.85, 0.6, 0.6, 0.6, 0.6]

# Link to networks in google drive folder
networks_drive_url: https://drive.google.com/drive/folders/1T8jqeyb10WrwnqQoMA25bRKQQvTacF6Y
# hand detection device = leap or hi5
hand_sensor: leap

misc_network_args:
  time_samples: 5

misc:
  rate: 10
  relevant_time: 0.5

# Mapping gesture ID to MotionPrimitiveID
# Mapping example:
# gestureID: MotionPrimitiveID
mappings:
  main_map:
    grab: gripper
    pinch: gripper
    point: focus
    two: focus
    three: focus
    four: move_block
    five: nothing
    thumbsup: gripper
    swipe_down: touch
    swipe_front_right: kick
    swipe_left: nothing
    swipe_up: go_to_home
    round: touch
    no_gesture: nothing
    # write about
    # solve RLBench task, push buttons in an order
  set0:
    grab: touch
    kick: kick
    nothing: nothing
    pinch: gripper
    victory: go_to_home
  set_1_static:
    grab: nothing
    pinch: nothing
    point: nothing
    respectful: nothing
    victory: nothing
    spock: nothing
    rock: nothing
  main_set_static:
    grab: nothing
    pinch: gripper
    point: nothing
    two: direction_move
    three: nothing
    four: nothing
    five: nothing
    thumbsup: nothing


  new_gesture_set:
    closed_hand: gripper
    opened_hand: gripper
    swipe_down: touch
    swipe_front_right: kick


















#
